BASE_TASK_CONFIG_PATH: habitat_extensions/config/vlnce_task_aug.yaml
TRAINER_NAME: decision_transformer # recollect_trainer, dagger
SIMULATOR_GPU_IDS: [1]
TORCH_GPU_ID: 1
NUM_ENVIRONMENTS: 2 #Looks like the sweet spot for dataset creation is 6 envs. If you use more, we might wait too long to reload the next batch....
TENSORBOARD_DIR: /cache/tensorboard-logdir/envdrop_batch_8_3l_8h_128d_lr-3_NDTWTG_STARTTOKEN_preload_256
CHECKPOINT_FOLDER: data/checkpoints/enhanced/envdrop_batch_8_3l_8h_128d_lr-3_NDTWTG_STARTTOKEN_preload_256
EVAL_CKPT_PATH_DIR: data/checkpoints/enhanced/envdrop_batch_8_3l_8h_128d_lr-3_NDTWTG_STARTTOKEN_preload_256
RESULTS_DIR: data/checkpoints/enhanced/envdrop_batch_8_3l_8h_128d_lr-3_NDTWTG_STARTTOKEN_preload_256/evals/debug
MULTIPROCESSING: forkserver  # default is forkserver, Set to 'spawn' when debugging with Pycharm,
ENV_NAME: VLNCEDecisionTransformerEnv


INFERENCE:
  SPLIT: test
  USE_CKPT_CONFIG: False
  SAMPLE: False
  CKPT_PATH: data/checkpoints/enhanced/envdrop_batch_8_3l_8h_128d_lr-3_NDTWTG_STARTTOKEN_preload_256/ckpt.269.pth
  PREDICTIONS_FILE: predictions.json
  FORMAT: r2r


EVAL:
  USE_CKPT_CONFIG: False
  SPLIT: debug # val_unseen
  EPISODE_COUNT: -1

IL:
  preload_dataloader_size: 256
  epochs: 51
  batch_size: 8
  checkpoint_frequency: 3
  lr: 2.5e-3
  load_from_ckpt: False # To train from a previous checkpoint
  ckpt_to_load: data/checkpoints/enhanced/envdrop_batch_8_3l_8h_128d_lr-3_NDTWTG_STARTTOKEN_preload_256/ckpt.7.pth # REPLACE

  RECOLLECT_TRAINER:
    gt_file:
      data/datasets/R2R_VLNCE_v1-3_preprocessed/{split}/{split}_gt.json.gz
  DECISION_TRANSFORMER:
    sensor_uuid: distance_left
    POINT_GOAL_NAV_REWARD:
      step_penalty: -0.01
      success: 1.0
    SPARSE_REWARD:
      step_penalty: -0.01
      success: 1.0
    NDTW_REWARD:
      step_penalty: -0.01
      success: 1.0
  DAGGER:
    repeat_dataset: 1
    iterations: 1
    update_size: 157232
    p: 1.0
    preload_lmdb_features: True
    lmdb_commit_frequency: 500
    lmdb_features_dir: data/trajectories_dirs/_aug_gold_/trajectories.lmdb


MODEL:
  DECISION_TRANSFORMER:
    net: DecisionTransformerEnhancedNet # DecisionTransformerNet or DecisionTransformerEnhancedNet
    use_extra_start_token: True
    reward_type: ndtw_reward_to_go # point_nav_reward_to_go, sparse_reward_to_go, point_nav_reward, sparse_reward, ndtw_reward, ndtw_reward_to_go
    n_layer: 3
    n_head: 8
    hidden_dim: 128 # The dimensions for the State, Reward and actions embeddings and in the GPT Backbne
  policy_name: DecisionTransformerPolicy
  PROGRESS_MONITOR:
    use: True
