BASE_TASK_CONFIG_PATH: habitat_extensions/config/vlnce_task.yaml
SIMULATOR_GPU_IDS: [0]
TORCH_GPU_ID: 0
NUM_ENVIRONMENTS: 5
TENSORBOARD_DIR: data/tensorboard_dirs/cma_pm_da_aug
CHECKPOINT_FOLDER: data/checkpoints/cma_pm_da_aug
EVAL_CKPT_PATH_DIR: data/checkpoints/cma_pm_da_aug
RESULTS_DIR: data/checkpoints/cma_pm_da_aug/evals

EVAL:
  USE_CKPT_CONFIG: False
  SPLIT: val_unseen
  EPISODE_COUNT: -1

IL:
  epochs: 4
  batch_size: 5
  load_from_ckpt: True # To train from a previous checkpoint
  ckpt_to_load: data/checkpoints/cma_pm_da_aug/CMA_PM_DA_Aug.pth # REPLACE
  DAGGER:
    iterations: 10
    update_size: 5000
    p: 0.75
    preload_lmdb_features: False
    lmdb_features_dir: data/trajectories_dirs/cma_pm_da_aug/trajectories.lmdb

MODEL:
  policy_name: CMAPolicy

  INSTRUCTION_ENCODER:
    bidirectional: True

  PROGRESS_MONITOR:
    use: True
