BASE_TASK_CONFIG_PATH: habitat_extensions/config/vlnce_task.yaml
TRAINER_NAME: decision_transformer # recollect_trainer, dagger
SIMULATOR_GPU_IDS: [1]
TORCH_GPU_ID: 1
NUM_ENVIRONMENTS: 15 #Only use one environment for Decision Transformer! An this is probably not working with MUlti Sim GPU
#TENSORBOARD_DIR: data/tensorboard_dirs/decision_transformer_v3_batch_8_3l_8h_128d_lr-3_NTG_STARTTOKEN_DAG_3_p_0.9
TENSORBOARD_DIR: /cache/tensorboard-logdir/decision_transformer_v3_batch_8_3l_8h_128d_lr-3_NTG_STARTTOKEN_DAG_3_p_0.9
CHECKPOINT_FOLDER: data/checkpoints/decision_transformer_v3_batch_8_3l_8h_128d_lr-3_NTG_STARTTOKEN_DAG_3_p_0.9
EVAL_CKPT_PATH_DIR: data/checkpoints/decision_transformer_v3_batch_8_3l_8h_128d_lr-3_NTG_STARTTOKEN_DAG_3_p_0.9
RESULTS_DIR: data/checkpoints/decision_transformer_v3_batch_8_3l_8h_128d_lr-3_NTG_STARTTOKEN_DAG_3_p_0.9/evals/val_seen
MULTIPROCESSING: forkserver  # default is forkserver, Set to 'spawn' when debugging with Pycharm,
ENV_NAME: VLNCEDecisionTransformerEnv

DATASET:
  TYPE: VLN-CE-v1
  SPLIT: train
  DATA_PATH: data/datasets/R2R_VLNCE_v1-3_preprocessed/{split}/{split}.json.gz
  SCENES_DIR: data/scene_datasets/

EVAL:
  USE_CKPT_CONFIG: False
  SPLIT: val_seen
  EPISODE_COUNT: -1

IL:
  epochs: 21
  batch_size: 8
  checkpoint_frequency: 3
  lr: 2.5e-3
  load_from_ckpt: True # To train from a previous checkpoint
  ckpt_to_load: /data/VLNCE/data/checkpoint/decision_transformer_v3_batch_8_3l_8h_128d_lr-3_NTG_STARTTOKEN_DAG_3_p_0.9/pretrained/ckpt.32.pth # REPLACE
  RECOLLECT_TRAINER:
    gt_file:
      data/datasets/R2R_VLNCE_v1-3_preprocessed/{split}/{split}_gt.json.gz
  DECISION_TRANSFORMER:
    sensor_uuid: distance_left
    POINT_GOAL_NAV_REWARD:
      step_penalty: -0.01
      success: 1.0
    SPARSE_REWARD:
      step_penalty: -0.01
      success: 1.0
  DAGGER:
    iterations: 5
    update_size: 5000
    p: 0.75
    preload_lmdb_features: False
    lmdb_commit_frequency: 500
    lmdb_features_dir: data/trajectories_dirs/decision_transformer_v3_batch_8_3l_8h_128d_lr-3_NTG_STARTTOKEN_DAG_3_p_0.9_DAG_3_p_0.9/trajectories.lmdb
    #lmdb_features_dir: data/trajectories_dirs/decision_transformer_PGR_1_-0.01_SR_1_-0.01/trajectories.lmdb
    #lmdb_features_dir: data/trajectories_dirs/decision_transformer_v2_debug/trajectories.lmdb

MODEL:
  DECISION_TRANSFORMER:
    use_extra_start_token: True
    reward_type: point_nav_reward_to_go # point_nav_reward_to_go, sparse_reward_to_go, point_nav_reward, sparse_reward
    n_layer: 3
    n_head: 8
    hidden_dim: 128 # The dimensions for the State, Reward and actions embeddings and in the GPT Backbne
  policy_name: DecisionTransformerPolicy
  PROGRESS_MONITOR:
    use: True
