BASE_TASK_CONFIG_PATH: habitat_extensions/config/vlnce_task.yaml
TRAINER_NAME: decision_transformer # recollect_trainer, dagger
SIMULATOR_GPU_IDS: [0]
TORCH_GPU_ID: 0
NUM_ENVIRONMENTS: 1
TENSORBOARD_DIR: data/tensorboard_dirs/decision_transformer
CHECKPOINT_FOLDER: data/checkpoints/decision_transformer
EVAL_CKPT_PATH_DIR: data/checkpoints/decision_transformer
RESULTS_DIR: data/checkpoints/decision_transformer/evals
MULTIPROCESSING: spawn  # default is forkserver, Set to 'spawn' when debugging with Pycharm,
ENV_NAME: VLNCEDecisionTransformerEnv


EVAL:
  USE_CKPT_CONFIG: False
  SPLIT: val_unseen
  EPISODE_COUNT: -1

IL:
  epochs: 15
  batch_size: 5

  RECOLLECT_TRAINER:
    gt_file:
      data/datasets/R2R_VLNCE_v1-3_preprocessed/{split}/{split}_gt.json.gz
  DECISION_TRANSFORMER:
    sensor_uuid: distance_left
    POINT_GOAL_NAV_REWARD:
      step_penalty: -0.01
      success: 10.0
    SPARSE_REWARD:
      step_penalty: -0.01
      success: 10.0

  DAGGER:
    iterations: 1
    update_size: 10819
    p: 1.0
    preload_lmdb_features: False
    lmdb_features_dir: data/trajectories_dirs/decision_transformer/trajectories.lmdb

MODEL:
  policy_name: DecisionTransformerPolicy
  PROGRESS_MONITOR:
    use: True
