BASE_TASK_CONFIG_PATH: habitat_extensions/config/vlnce_task_aug_50plus.yaml
TRAINER_NAME: decision_transformer # recollect_trainer, dagger
SIMULATOR_GPU_IDS: [0,1] # Be careful: not having the correct IDs might lead to EGL errors
TORCH_GPU_ID: 0
NUM_ENVIRONMENTS: 15 #Only use one environment for Decision Transformer! An this is probably not working with MUlti Sim GPU
TENSORBOARD_DIR: data/tensorboard_dirs/decision_transformer_aug_v3
CHECKPOINT_FOLDER: data/checkpoints/decision_transformer_aug_v3
EVAL_CKPT_PATH_DIR: data/checkpoints/decision_transformer_aug_v3
RESULTS_DIR: data/checkpoints/decision_transformer_aug_v3/evals/debug
MULTIPROCESSING: forkserver  # default is forkserver, Set to 'spawn' when debugging with Pycharm,
ENV_NAME: VLNCEDecisionTransformerEnv


EVAL:
  USE_CKPT_CONFIG: False
  SPLIT: debug
  EPISODE_COUNT: -1

IL:
  preload_dataloader_size: 128
  epochs: 45
  batch_size: 32
  checkpoint_frequency: 3
  lr: 2.5e-3
  load_from_ckpt: False # To train from a previous checkpoint
  ckpt_to_load: data/checkpoints/cma_pm_aug/best_checkpoint.pth # REPLACE
  RECOLLECT_TRAINER:
    gt_file:
      data/datasets/R2R_VLNCE_v1-3_preprocessed/{split}/{split}_gt.json.gz
  DECISION_TRANSFORMER:
    sensor_uuid: distance_left
    POINT_GOAL_NAV_REWARD:
      step_penalty: -0.01
      success: 1.0
    SPARSE_REWARD:
      step_penalty: -0.01
      success: 1.0
    NDTW_REWARD:
      step_penalty: -0.01
      success: 1.0
  DAGGER:
    iterations: 1
    update_size: 157232
    p: 1.0
    preload_lmdb_features: True
    lmdb_commit_frequency: 500
    lmdb_features_dir: data/trajectories_dirs/decision_transformer_aug_v3_PGR_1_-0.01_SR_1_-0.01_NDTWR_1_-0.01/trajectories.lmdb
    #lmdb_features_dir: data/trajectories_dirs/decision_transformer_PGR_1_-0.01_SR_1_-0.01/trajectories.lmdb
    #lmdb_features_dir: data/trajectories_dirs/decision_transformer_v2_debug/trajectories.lmdb

MODEL:
  DECISION_TRANSFORMER:
    use_extra_start_token: True
    reward_type: point_nav_reward_to_go # point_nav_reward_to_go, sparse_reward_to_go, point_nav_reward, sparse_reward, ndtw_reward, ndtw_reward_to_go
    n_layer: 3
    n_head: 8
    hidden_dim: 128 # The dimensions for the State, Reward and actions embeddings and in the GPT Backbne
  policy_name: DecisionTransformerPolicy
  PROGRESS_MONITOR:
    use: True
