BASE_TASK_CONFIG_PATH: habitat_extensions/config/vlnce_task.yaml
TRAINER_NAME: decision_transformer # recollect_trainer, dagger
SIMULATOR_GPU_IDS: [0]
TORCH_GPU_ID: 0
NUM_ENVIRONMENTS: 6 #Looks like the sweet spot for dataset creation is 6 envs. If you use more, we might wait too long to reload the next batch....
TENSORBOARD_DIR: data/tensorboard_dirs/repeat_batch_8_3l_8h_128d_lr-3_NTG_STARTTOKEN_preload_128
CHECKPOINT_FOLDER: data/checkpoints/repeat_batch_8_3l_8h_128d_lr-3_NTG_STARTTOKEN_preload_128
EVAL_CKPT_PATH_DIR: data/checkpoints/repeat_batch_8_3l_8h_128d_lr-3_NTG_STARTTOKEN_preload_128
RESULTS_DIR: data/checkpoints/repeat_batch_8_3l_8h_128d_lr-3_NTG_STARTTOKEN_preload_128/evals/val_unseen
MULTIPROCESSING: forkserver  # default is forkserver, Set to 'spawn' when debugging with Pycharm,
ENV_NAME: VLNCEDecisionTransformerEnv


INFERENCE:
  SPLIT: test
  USE_CKPT_CONFIG: False
  SAMPLE: False
  CKPT_PATH: data/checkpoints/repeat_batch_8_3l_8h_128d_lr-3_NTG_STARTTOKEN_preload_128/ckpt.269.pth
  PREDICTIONS_FILE: predictions.json
  FORMAT: r2r


EVAL:
  USE_CKPT_CONFIG: False
  SPLIT: val_unseen # val_unseen
  EPISODE_COUNT: -1

IL:
  preload_dataloader_size: 128
  epochs: 15
  batch_size: 8
  checkpoint_frequency: 3
  lr: 2.5e-3
  load_from_ckpt: False # To train from a previous checkpoint
  ckpt_to_load: data/checkpoints/repeat_batch_8_3l_8h_128d_lr-3_NTG_STARTTOKEN_preload_128/ckpt.7.pth # REPLACE

  RECOLLECT_TRAINER:
    gt_file:
      data/datasets/R2R_VLNCE_v1-3_preprocessed/{split}/{split}_gt.json.gz
  DECISION_TRANSFORMER:
    sensor_uuid: distance_left
    POINT_GOAL_NAV_REWARD:
      step_penalty: -0.01
      success: 1.0
    SPARSE_REWARD:
      step_penalty: -0.01
      success: 1.0
    NDTW_REWARD:
      step_penalty: -0.01
      success: 1.0
  DAGGER:
    repeat_dataset: 8
    iterations: 1
    update_size: 10819
    p: 1.0
    preload_lmdb_features: True
    lmdb_commit_frequency: 500
    lmdb_features_dir: data/trajectories_dirs/_GOLD_REPEAT_/trajectories.lmdb


MODEL:
  DECISION_TRANSFORMER:
    net: DecisionTransformerNet # DecisionTransformerNet or DecisionTransformerEnhancedNet
    use_extra_start_token: True
    reward_type: point_nav_reward_to_go # point_nav_reward_to_go, sparse_reward_to_go, point_nav_reward, sparse_reward, ndtw_reward, ndtw_reward_to_go
    n_layer: 3
    n_head: 8
    hidden_dim: 128 # The dimensions for the State, Reward and actions embeddings and in the GPT Backbne
  policy_name: DecisionTransformerPolicy
  PROGRESS_MONITOR:
    use: True
