BASE_TASK_CONFIG_PATH: habitat_extensions/config/vlnce_task.yaml
TRAINER_NAME: decision_transformer # recollect_trainer, dagger
SIMULATOR_GPU_IDS: [0]
TORCH_GPU_ID: 0
NUM_ENVIRONMENTS: 4 #Only use one environment for Decision Transformer! An this is probably not working with MUlti Sim GPU
TENSORBOARD_DIR: data/tensorboard_dirs/decision_transformer_debug_rgb_depth_mean
CHECKPOINT_FOLDER: data/checkpoints/decision_transformer_debug_rgb_depth_mean
EVAL_CKPT_PATH_DIR: data/checkpoints/decision_transformer_debug_rgb_depth_mean
RESULTS_DIR: data/checkpoints/decision_transformer_debug_rgb_depth_mean/evals
MULTIPROCESSING: forkserver  # default is forkserver, Set to 'spawn' when debugging with Pycharm,
ENV_NAME: VLNCEDecisionTransformerEnv


INFERENCE:
  SPLIT: debug
  USE_CKPT_CONFIG: False
  SAMPLE: False
  CKPT_PATH: data/checkpoints/decision_transformer_debug_rgb_depth_mean/ckpt.269.pth
  PREDICTIONS_FILE: predictions.json
  FORMAT: r2r


EVAL:
  USE_CKPT_CONFIG: False
  SPLIT: debug
  EPISODE_COUNT: -1
  VAL_SEEN: "val_seen"
  VAL_UNSEEN: "val_unseen"

IL:
  preload_dataloader_size: 200
  dataload_workers: 1
  epochs: 42
  batch_size: 16
  checkpoint_frequency: 1
  mean_loss_to_save_checkpoint: 0.35
  lr: 1.5e-4
  load_from_ckpt: False # To train from a previous checkpoint
  ckpt_to_load: data/checkpoints/decision_transformer_debug_rgb_depth_mean/ckpt.269.pth # REPLACE

  RECOLLECT_TRAINER:
    gt_file:
      data/datasets/R2R_VLNCE_v1-3_preprocessed/{split}/{split}_gt.json.gz
  DECISION_TRANSFORMER:
    recompute_reward: True # allows to apply step penalty and end reward on the fly without recaching the whole dataset...
    sensor_uuid: distance_left
    POINT_GOAL_NAV_REWARD:
      step_penalty: -0.2
      success: 1.0
    SPARSE_REWARD:
      step_penalty: -0.01
      success: 1.0
    NDTW_REWARD:
      step_penalty: -0.01
      success: 1.0
  DAGGER:
    repeat_dataset: 1
    iterations: 1
    update_size: 10819
    p: 1.0
    preload_lmdb_features: False
    lmdb_commit_frequency: 500
    lmdb_features_dir: data/trajectories_dirs/decision_transformer_rgb_depth_mean/trajectories.lmdb


MODEL:
  DECISION_TRANSFORMER:
    # Possible values: DecisionTransformerNet, DecisionTransformerfullNet
    # DecisionTransformerWithAttendedInstructionsNet or  FullDecisionTransformerNet
    net: FullDecisionTransformerNet
    use_extra_start_token: True
    reward_type: point_nav_reward_to_go # point_nav_reward_to_go, sparse_reward_to_go, point_nav_reward, sparse_reward, ndtw_reward, ndtw_reward_to_go
    n_layer: 3
    n_head: 8
    hidden_dim: 128 # The dimensions for the State, Reward and actions embeddings and in the GPT Backbne
    use_transformer_encoded_instruction: False # only for DecisionTransformerNet, DecisionTransformerfullNet
    activation_action_drop: 0.25
    activation_instruction_drop: 0.01
    activation_rgb_drop: 0.01
    activation_depth_drop: 0.01
    normalize_rgb: True
    normalize_depth: True
    ENCODER: # only for FullDecisionTransformerNet
      n_layer: 3
      n_head: 8
      use_output_rgb_instructions: True # different instructions for each time steps attended by RGB
      use_output_depth_instructions: True # different instructions for each time steps attended by depth
      use_output_rgb: False # global RGB attended by instruction
      use_output_depth: False # global Depth attended by instruction
  policy_name: DecisionTransformerPolicy
  PROGRESS_MONITOR: # This is only used to create the datasets and the reward signals
    use: True

